plugins {
    id 'com.android.application'
}

android {
    namespace 'com.aqiffarooqui.muslimummah'
    compileSdk 35

    defaultConfig {
        applicationId 'com.aqiffarooqui.muslimummah'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

dependencies {
}
