import React,{useCallback,useEffect,useState}from'react';
import{Alert,Platform,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{Ionicons}from'@expo/vector-icons';
import{usePremium}from'./PremiumProvider';
import{getBookmarks}from'../quranBookmarks';
import{getQuranProgress}from'../quranProgress';
import{getLastCloudSync,restorePremiumData,syncPremiumData}from'./cloudSyncService';
import{cancelAllReminders,getScheduledReminderCount,scheduleDailyIslamicReminder}from'./reminderService';
export default function PremiumToolsScreen({onBack}:{onBack:()=>void}){
const{isPremium}=usePremium();const[bookmarks,setBookmarks]=useState(0);const[progress,setProgress]=useState({surahNumber:1,ayahNumber:1});const[sync,setSync]=useState<string|null>(null);const[reminders,setReminders]=useState(0);const[busy,setBusy]=useState(false);
const load=useCallback(async()=>{setBookmarks(getBookmarks().length);const p=await getQuranProgress();if(p)setProgress(p);setSync(await getLastCloudSync());setReminders(await getScheduledReminderCount())},[]);useEffect(()=>{load()},[load]);
const notify=(title:string,msg:string)=>Platform.OS==='web'?window.alert(title+'\n\n'+msg):Alert.alert(title,msg);
const run=async(fn:()=>Promise<void>,ok:string)=>{try{setBusy(true);await fn();await load();notify('Muslim Ummah',ok)}catch(e){notify('Unable to complete',e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}};
if(!isPremium)return <View style={s.center}><Ionicons name='lock-closed' size={38} color='#D8B36A'/><Text style={s.title}>Premium Required</Text><Text style={s.text}>Unlock Insights, Reminders and Cloud Sync from Premium.</Text><Pressable style={s.primary} onPress={onBack}><Text style={s.primaryText}>Back</Text></Pressable></View>;
return <View style={s.container}><ScrollView contentContainerStyle={s.content}><View style={s.header}><Pressable onPress={onBack}style={s.back}><Ionicons name='arrow-back' size={21} color='#fff'/></Pressable><Text style={s.headerTitle}>Premium Tools</Text></View>
<View style={s.hero}><Ionicons name='sparkles' size={28} color='#D8B36A'/><Text style={s.heroTitle}>Your Premium Experience</Text><Text style={s.text}>Live personal data — no dummy statistics.</Text></View>
<Text style={s.section}>Reading Insights</Text><View style={s.grid}><Stat icon='bookmark-outline' label='Saved Ayahs' value={bookmarks}/><Stat icon='book-outline' label='Current Surah' value={progress.surahNumber}/><Stat icon='flag-outline' label='Current Ayah' value={progress.ayahNumber}/></View>
<Text style={s.section}>Cloud Sync</Text><View style={s.card}><Ionicons name='cloud-outline' size={25} color='#D8B36A'/><View style={s.flex}><Text style={s.cardTitle}>Sync Quran progress & bookmarks</Text><Text style={s.text}>{sync?'Last sync: '+new Date(sync).toLocaleString():'Not synced yet'}</Text></View></View>
<View style={s.row}><Pressable disabled={busy}style={s.action}onPress={()=>run(syncPremiumData,'Your Quran data was synced to Firebase.')}><Text style={s.actionText}>Sync Now</Text></Pressable><Pressable disabled={busy}style={s.action}onPress={async()=>{try{setBusy(true);const data=await restorePremiumData();notify('Cloud Sync',data?'Cloud data found: '+data.bookmarks.length+' bookmarks.':'No cloud data found.')}finally{setBusy(false)}}}><Text style={s.actionText}>Check Cloud</Text></Pressable></View>
<Text style={s.section}>Advanced Reminders</Text><View style={s.card}><Ionicons name='notifications-outline' size={25} color='#D8B36A'/><View style={s.flex}><Text style={s.cardTitle}>Daily Islamic reminder</Text><Text style={s.text}>{reminders} scheduled notification(s)</Text></View></View>
<View style={s.row}><Pressable disabled={busy}style={s.action}onPress={()=>run(async()=>{await scheduleDailyIslamicReminder(9,0)},'Daily reminder scheduled for 9:00 AM.')}><Text style={s.actionText}>Schedule 9 AM</Text></Pressable><Pressable disabled={busy}style={s.danger}onPress={()=>run(cancelAllReminders,'All scheduled reminders cancelled.')}><Text style={s.dangerText}>Cancel All</Text></Pressable></View>
<View style={s.note}><Text style={s.text}>These reminders use real device scheduling. Prayer-specific reminders will use the live Prayer Times data when that module is connected.</Text></View></ScrollView></View>}
function Stat({icon,label,value}:{icon:keyof typeof Ionicons.glyphMap;label:string;value:number}){return <View style={s.stat}><Ionicons name={icon}size={22}color='#D8B36A'/><Text style={s.statLabel}>{label}</Text><Text style={s.statValue}>{value}</Text></View>}
const s=StyleSheet.create({container:{flex:1,backgroundColor:'#080A0F'},content:{padding:18,paddingBottom:50},center:{flex:1,backgroundColor:'#080A0F',alignItems:'center',justifyContent:'center',padding:25},header:{flexDirection:'row',alignItems:'center',gap:12,marginBottom:18},back:{width:42,height:42,borderRadius:14,backgroundColor:'#151922',alignItems:'center',justifyContent:'center'},headerTitle:{color:'#fff',fontSize:20,fontWeight:'800'},hero:{padding:20,borderRadius:22,backgroundColor:'#151922',borderWidth:1,borderColor:'#292E39',alignItems:'center'},heroTitle:{color:'#fff',fontSize:19,fontWeight:'800',marginTop:10},title:{color:'#fff',fontSize:22,fontWeight:'800',marginTop:14},text:{color:'#858B99',fontSize:11,lineHeight:17,marginTop:4},section:{color:'#fff',fontSize:18,fontWeight:'800',marginTop:25,marginBottom:10},grid:{flexDirection:'row',gap:8},stat:{flex:1,minHeight:105,padding:13,borderRadius:17,backgroundColor:'#10131A',borderWidth:1,borderColor:'#252A35'},statLabel:{color:'#7B828F',fontSize:9,fontWeight:'800',marginTop:12},statValue:{color:'#D8B36A',fontSize:24,fontWeight:'900',marginTop:4},card:{padding:15,borderRadius:18,backgroundColor:'#10131A',borderWidth:1,borderColor:'#252A35',flexDirection:'row',alignItems:'center',gap:12},flex:{flex:1},cardTitle:{color:'#eee',fontSize:12,fontWeight:'800'},row:{flexDirection:'row',gap:8,marginTop:9},action:{flex:1,padding:12,borderRadius:13,backgroundColor:'#211F18',borderWidth:1,borderColor:'#806B3D',alignItems:'center'},actionText:{color:'#D8B36A',fontSize:10,fontWeight:'900'},danger:{flex:1,padding:12,borderRadius:13,backgroundColor:'#241417',borderWidth:1,borderColor:'#663038',alignItems:'center'},dangerText:{color:'#E9A5AB',fontSize:10,fontWeight:'900'},primary:{marginTop:18,paddingHorizontal:22,paddingVertical:12,borderRadius:14,backgroundColor:'#D8B36A'},primaryText:{color:'#080A0F',fontWeight:'900'},note:{marginTop:20,padding:13,borderRadius:15,backgroundColor:'#11141B',borderWidth:1,borderColor:'#252A35'}});