package com.aqiffarooqui.muslimummah;

public final class QuranData {
  public static final class Surah {
    public final int number, ayahCount; public final String name, arabicName, englishName, revelation;
    public Surah(int number,String name,String arabicName,String englishName,String revelation,int ayahCount){this.number=number;this.name=name;this.arabicName=arabicName;this.englishName=englishName;this.revelation=revelation;this.ayahCount=ayahCount;}
  }
  public static final Surah[] SURAHS = new Surah[]{
    new Surah(1,"Al-Fatihah","الفاتحة","The Opening","Meccan",7),
    new Surah(2,"Al-Baqarah","البقرة","The Cow","Medinan",286),
    new Surah(3,"Aal-E-Imran","آل عمران","Family of Imran","Medinan",200),
    new Surah(4,"An-Nisa","النساء","The Women","Medinan",176),
    new Surah(5,"Al-Ma'idah","المائدة","The Table Spread","Medinan",120),
    new Surah(6,"Al-An'am","الأنعام","The Cattle","Meccan",165),
    new Surah(7,"Al-A'raf","الأعراف","The Heights","Meccan",206),
    new Surah(8,"Al-Anfal","الأنفال","The Spoils of War","Medinan",75),
    new Surah(9,"At-Tawbah","التوبة","The Repentance","Medinan",129),
    new Surah(10,"Yunus","يونس","Jonah","Meccan",109),
    new Surah(11,"Hud","هود","Hud","Meccan",123),
    new Surah(12,"Yusuf","يوسف","Joseph","Meccan",111),
    new Surah(13,"Ar-Ra'd","الرعد","The Thunder","Medinan",43),
    new Surah(14,"Ibrahim","إبراهيم","Abraham","Meccan",52),
    new Surah(15,"Al-Hijr","الحجر","The Rocky Tract","Meccan",99),
    new Surah(16,"An-Nahl","النحل","The Bee","Meccan",128),
    new Surah(17,"Al-Isra","الإسراء","The Night Journey","Meccan",111),
    new Surah(18,"Al-Kahf","الكهف","The Cave","Meccan",110),
    new Surah(19,"Maryam","مريم","Mary","Meccan",98),
    new Surah(20,"Ta-Ha","طه","Ta-Ha","Meccan",135),
    new Surah(21,"Al-Anbiya","الأنبياء","The Prophets","Meccan",112),
    new Surah(22,"Al-Hajj","الحج","The Pilgrimage","Medinan",78),
    new Surah(23,"Al-Mu'minun","المؤمنون","The Believers","Meccan",118),
    new Surah(24,"An-Nur","النور","The Light","Medinan",64),
    new Surah(25,"Al-Furqan","الفرقان","The Criterion","Meccan",77),
    new Surah(26,"Ash-Shu'ara","الشعراء","The Poets","Meccan",227),
    new Surah(27,"An-Naml","النمل","The Ant","Meccan",93),
    new Surah(28,"Al-Qasas","القصص","The Stories","Meccan",88),
    new Surah(29,"Al-Ankabut","العنكبوت","The Spider","Meccan",69),
    new Surah(30,"Ar-Rum","الروم","The Romans","Meccan",60),
    new Surah(31,"Luqman","لقمان","Luqman","Meccan",34),
    new Surah(32,"As-Sajdah","السجدة","The Prostration","Meccan",30),
    new Surah(33,"Al-Ahzab","الأحزاب","The Combined Forces","Medinan",73),
    new Surah(34,"Saba","سبأ","Sheba","Meccan",54),
    new Surah(35,"Fatir","فاطر","Originator","Meccan",45),
    new Surah(36,"Ya-Sin","يس","Ya-Sin","Meccan",83),
    new Surah(37,"As-Saffat","الصافات","Those Who Set The Ranks","Meccan",182),
    new Surah(38,"Sad","ص","Sad","Meccan",88),
    new Surah(39,"Az-Zumar","الزمر","The Groups","Meccan",75),
    new Surah(40,"Ghafir","غافر","The Forgiver","Meccan",85),
    new Surah(41,"Fussilat","فصلت","Explained in Detail","Meccan",54),
    new Surah(42,"Ash-Shura","الشورى","The Consultation","Meccan",53),
    new Surah(43,"Az-Zukhruf","الزخرف","The Ornaments of Gold","Meccan",89),
    new Surah(44,"Ad-Dukhan","الدخان","The Smoke","Meccan",59),
    new Surah(45,"Al-Jathiyah","الجاثية","The Crouching","Meccan",37),
    new Surah(46,"Al-Ahqaf","الأحقاف","The Wind-Curved Sandhills","Meccan",35),
    new Surah(47,"Muhammad","محمد","Muhammad","Medinan",38),
    new Surah(48,"Al-Fath","الفتح","The Victory","Medinan",29),
    new Surah(49,"Al-Hujurat","الحجرات","The Rooms","Medinan",18),
    new Surah(50,"Qaf","ق","Qaf","Meccan",45),
    new Surah(51,"Adh-Dhariyat","الذاريات","The Winnowing Winds","Meccan",60),
    new Surah(52,"At-Tur","الطور","The Mount","Meccan",49),
    new Surah(53,"An-Najm","النجم","The Star","Meccan",62),
    new Surah(54,"Al-Qamar","القمر","The Moon","Meccan",55),
    new Surah(55,"Ar-Rahman","الرحمن","The Beneficent","Medinan",78),
    new Surah(56,"Al-Waqi'ah","الواقعة","The Inevitable","Meccan",96),
    new Surah(57,"Al-Hadid","الحديد","The Iron","Medinan",29),
    new Surah(58,"Al-Mujadilah","المجادلة","The Pleading Woman","Medinan",22),
    new Surah(59,"Al-Hashr","الحشر","The Exile","Medinan",24),
    new Surah(60,"Al-Mumtahanah","الممتحنة","She That Is To Be Examined","Medinan",13),
    new Surah(61,"As-Saff","الصف","The Ranks","Medinan",14),
    new Surah(62,"Al-Jumu'ah","الجمعة","Friday","Medinan",11),
    new Surah(63,"Al-Munafiqun","المنافقون","The Hypocrites","Medinan",11),
    new Surah(64,"At-Taghabun","التغابن","The Mutual Disillusion","Medinan",18),
    new Surah(65,"At-Talaq","الطلاق","The Divorce","Medinan",12),
    new Surah(66,"At-Tahrim","التحريم","The Prohibition","Medinan",12),
    new Surah(67,"Al-Mulk","الملك","The Sovereignty","Meccan",30),
    new Surah(68,"Al-Qalam","القلم","The Pen","Meccan",52),
    new Surah(69,"Al-Haqqah","الحاقة","The Reality","Meccan",52),
    new Surah(70,"Al-Ma'arij","المعارج","The Ascending Stairways","Meccan",44),
    new Surah(71,"Nuh","نوح","Noah","Meccan",28),
    new Surah(72,"Al-Jinn","الجن","The Jinn","Meccan",28),
    new Surah(73,"Al-Muzzammil","المزمل","The Enshrouded One","Meccan",20),
    new Surah(74,"Al-Muddaththir","المدثر","The Cloaked One","Meccan",56),
    new Surah(75,"Al-Qiyamah","القيامة","The Resurrection","Meccan",40),
    new Surah(76,"Al-Insan","الإنسان","The Man","Medinan",31),
    new Surah(77,"Al-Mursalat","المرسلات","Those Sent Forth","Meccan",50),
    new Surah(78,"An-Naba","النبأ","The Tidings","Meccan",40),
    new Surah(79,"An-Naziat","النازعات","Those Who Drag Forth","Meccan",46),
    new Surah(80,"Abasa","عبس","He Frowned","Meccan",42),
    new Surah(81,"At-Takwir","التكوير","The Overthrowing","Meccan",29),
    new Surah(82,"Al-Infitar","الانفطار","The Cleaving","Meccan",19),
    new Surah(83,"Al-Mutaffifin","المطففين","The Defrauding","Meccan",36),
    new Surah(84,"Al-Inshiqaq","الانشقاق","The Sundering","Meccan",25),
    new Surah(85,"Al-Buruj","البروج","The Mansions of the Stars","Meccan",22),
    new Surah(86,"At-Tariq","الطارق","The Nightcomer","Meccan",17),
    new Surah(87,"Al-A'la","الأعلى","The Most High","Meccan",19),
    new Surah(88,"Al-Ghashiyah","الغاشية","The Overwhelming","Meccan",26),
    new Surah(89,"Al-Fajr","الفجر","The Dawn","Meccan",30),
    new Surah(90,"Al-Balad","البلد","The City","Meccan",20),
    new Surah(91,"Ash-Shams","الشمس","The Sun","Meccan",15),
    new Surah(92,"Al-Layl","الليل","The Night","Meccan",21),
    new Surah(93,"Ad-Duha","الضحى","The Morning Hours","Meccan",11),
    new Surah(94,"Ash-Sharh","الشرح","The Relief","Meccan",8),
    new Surah(95,"At-Tin","التين","The Fig","Meccan",8),
    new Surah(96,"Al-Alaq","العلق","The Clot","Meccan",19),
    new Surah(97,"Al-Qadr","القدر","The Power","Meccan",5),
    new Surah(98,"Al-Bayyinah","البينة","The Clear Evidence","Medinan",8),
    new Surah(99,"Az-Zalzalah","الزلزلة","The Earthquake","Medinan",8),
    new Surah(100,"Al-Adiyat","العاديات","The Courser","Meccan",11),
    new Surah(101,"Al-Qari'ah","القارعة","The Striking Hour","Meccan",11),
    new Surah(102,"At-Takathur","التكاثر","The Rivalry in World Increase","Meccan",8),
    new Surah(103,"Al-Asr","العصر","The Declining Day","Meccan",3),
    new Surah(104,"Al-Humazah","الهمزة","The Traducer","Meccan",9),
    new Surah(105,"Al-Fil","الفيل","The Elephant","Meccan",5),
    new Surah(106,"Quraysh","قريش","Quraysh","Meccan",4),
    new Surah(107,"Al-Ma'un","الماعون","The Small Kindnesses","Meccan",7),
    new Surah(108,"Al-Kawthar","الكوثر","The Abundance","Meccan",3),
    new Surah(109,"Al-Kafirun","الكافرون","The Disbelievers","Meccan",6),
    new Surah(110,"An-Nasr","النصر","The Divine Support","Medinan",3),
    new Surah(111,"Al-Masad","المسد","The Palm Fiber","Meccan",5),
    new Surah(112,"Al-Ikhlas","الإخلاص","The Sincerity","Meccan",4),
    new Surah(113,"Al-Falaq","الفلق","The Daybreak","Meccan",5),
    new Surah(114,"An-Nas","الناس","Mankind","Meccan",6)
  };
  private QuranData(){}
}
