export type Surah = {
  number: number;
  name: string;
  arabicName: string;
  englishName: string;
  revelation: 'Meccan' | 'Medinan';
  ayahCount: number;
};

export const SURAHS: Surah[] = [
  {
    number: 1,
    name: 'Al-Fatihah',
    arabicName: 'الفاتحة',
    englishName: 'The Opening',
    revelation: 'Meccan',
    ayahCount: 7,
  },
  {
    number: 2,
    name: 'Al-Baqarah',
    arabicName: 'البقرة',
    englishName: 'The Cow',
    revelation: 'Medinan',
    ayahCount: 286,
  },
  {
    number: 3,
    name: 'Aal-E-Imran',
    arabicName: 'آل عمران',
    englishName: 'Family of Imran',
    revelation: 'Medinan',
    ayahCount: 200,
  },
  {
    number: 4,
    name: 'An-Nisa',
    arabicName: 'النساء',
    englishName: 'The Women',
    revelation: 'Medinan',
    ayahCount: 176,
  },
  {
    number: 5,
    name: "Al-Ma'idah",
    arabicName: 'المائدة',
    englishName: 'The Table Spread',
    revelation: 'Medinan',
    ayahCount: 120,
  },
  {
    number: 6,
    name: "Al-An'am",
    arabicName: 'الأنعام',
    englishName: 'The Cattle',
    revelation: 'Meccan',
    ayahCount: 165,
  },
  {
    number: 7,
    name: "Al-A'raf",
    arabicName: 'الأعراف',
    englishName: 'The Heights',
    revelation: 'Meccan',
    ayahCount: 206,
  },
  {
    number: 8,
    name: 'Al-Anfal',
    arabicName: 'الأنفال',
    englishName: 'The Spoils of War',
    revelation: 'Medinan',
    ayahCount: 75,
  },
  {
    number: 9,
    name: 'At-Tawbah',
    arabicName: 'التوبة',
    englishName: 'The Repentance',
    revelation: 'Medinan',
    ayahCount: 129,
  },
  {
    number: 10,
    name: 'Yunus',
    arabicName: 'يونس',
    englishName: 'Jonah',
    revelation: 'Meccan',
    ayahCount: 109,
  },
  {
    number: 11,
    name: 'Hud',
    arabicName: 'هود',
    englishName: 'Hud',
    revelation: 'Meccan',
    ayahCount: 123,
  },
  {
    number: 12,
    name: 'Yusuf',
    arabicName: 'يوسف',
    englishName: 'Joseph',
    revelation: 'Meccan',
    ayahCount: 111,
  },
  {
    number: 13,
    name: "Ar-Ra'd",
    arabicName: 'الرعد',
    englishName: 'The Thunder',
    revelation: 'Medinan',
    ayahCount: 43,
  },
  {
    number: 14,
    name: 'Ibrahim',
    arabicName: 'إبراهيم',
    englishName: 'Abraham',
    revelation: 'Meccan',
    ayahCount: 52,
  },
  {
    number: 15,
    name: 'Al-Hijr',
    arabicName: 'الحجر',
    englishName: 'The Rocky Tract',
    revelation: 'Meccan',
    ayahCount: 99,
  },
  {
    number: 16,
    name: 'An-Nahl',
    arabicName: 'النحل',
    englishName: 'The Bee',
    revelation: 'Meccan',
    ayahCount: 128,
  },
  {
    number: 17,
    name: 'Al-Isra',
    arabicName: 'الإسراء',
    englishName: 'The Night Journey',
    revelation: 'Meccan',
    ayahCount: 111,
  },
  {
    number: 18,
    name: 'Al-Kahf',
    arabicName: 'الكهف',
    englishName: 'The Cave',
    revelation: 'Meccan',
    ayahCount: 110,
  },
  {
    number: 19,
    name: 'Maryam',
    arabicName: 'مريم',
    englishName: 'Mary',
    revelation: 'Meccan',
    ayahCount: 98,
  },
  {
    number: 20,
    name: 'Ta-Ha',
    arabicName: 'طه',
    englishName: 'Ta-Ha',
    revelation: 'Meccan',
    ayahCount: 135,
  },
  {
    number: 21,
    name: 'Al-Anbiya',
    arabicName: 'الأنبياء',
    englishName: 'The Prophets',
    revelation: 'Meccan',
    ayahCount: 112,
  },
  {
    number: 22,
    name: 'Al-Hajj',
    arabicName: 'الحج',
    englishName: 'The Pilgrimage',
    revelation: 'Medinan',
    ayahCount: 78,
  },
  {
    number: 23,
    name: "Al-Mu'minun",
    arabicName: 'المؤمنون',
    englishName: 'The Believers',
    revelation: 'Meccan',
    ayahCount: 118,
  },
  {
    number: 24,
    name: 'An-Nur',
    arabicName: 'النور',
    englishName: 'The Light',
    revelation: 'Medinan',
    ayahCount: 64,
  },
  {
    number: 25,
    name: 'Al-Furqan',
    arabicName: 'الفرقان',
    englishName: 'The Criterion',
    revelation: 'Meccan',
    ayahCount: 77,
  },
  {
    number: 26,
    name: "Ash-Shu'ara",
    arabicName: 'الشعراء',
    englishName: 'The Poets',
    revelation: 'Meccan',
    ayahCount: 227,
  },
  {
    number: 27,
    name: 'An-Naml',
    arabicName: 'النمل',
    englishName: 'The Ant',
    revelation: 'Meccan',
    ayahCount: 93,
  },
  {
    number: 28,
    name: 'Al-Qasas',
    arabicName: 'القصص',
    englishName: 'The Stories',
    revelation: 'Meccan',
    ayahCount: 88,
  },
  {
    number: 29,
    name: 'Al-Ankabut',
    arabicName: 'العنكبوت',
    englishName: 'The Spider',
    revelation: 'Meccan',
    ayahCount: 69,
  },
  {
    number: 30,
    name: 'Ar-Rum',
    arabicName: 'الروم',
    englishName: 'The Romans',
    revelation: 'Meccan',
    ayahCount: 60,
  },
  {
    number: 31,
    name: 'Luqman',
    arabicName: 'لقمان',
    englishName: 'Luqman',
    revelation: 'Meccan',
    ayahCount: 34,
  },
  {
    number: 32,
    name: 'As-Sajdah',
    arabicName: 'السجدة',
    englishName: 'The Prostration',
    revelation: 'Meccan',
    ayahCount: 30,
  },
  {
    number: 33,
    name: 'Al-Ahzab',
    arabicName: 'الأحزاب',
    englishName: 'The Combined Forces',
    revelation: 'Medinan',
    ayahCount: 73,
  },
  {
    number: 34,
    name: 'Saba',
    arabicName: 'سبأ',
    englishName: 'Sheba',
    revelation: 'Meccan',
    ayahCount: 54,
  },
  {
    number: 35,
    name: 'Fatir',
    arabicName: 'فاطر',
    englishName: 'Originator',
    revelation: 'Meccan',
    ayahCount: 45,
  },
  {
    number: 36,
    name: 'Ya-Sin',
    arabicName: 'يس',
    englishName: 'Ya-Sin',
    revelation: 'Meccan',
    ayahCount: 83,
  },
  {
    number: 37,
    name: 'As-Saffat',
    arabicName: 'الصافات',
    englishName: 'Those Who Set The Ranks',
    revelation: 'Meccan',
    ayahCount: 182,
  },
  {
    number: 38,
    name: 'Sad',
    arabicName: 'ص',
    englishName: 'Sad',
    revelation: 'Meccan',
    ayahCount: 88,
  },
  {
    number: 39,
    name: 'Az-Zumar',
    arabicName: 'الزمر',
    englishName: 'The Groups',
    revelation: 'Meccan',
    ayahCount: 75,
  },
  {
    number: 40,
    name: 'Ghafir',
    arabicName: 'غافر',
    englishName: 'The Forgiver',
    revelation: 'Meccan',
    ayahCount: 85,
  },
  {
    number: 41,
    name: 'Fussilat',
    arabicName: 'فصلت',
    englishName: 'Explained in Detail',
    revelation: 'Meccan',
    ayahCount: 54,
  },
  {
    number: 42,
    name: 'Ash-Shura',
    arabicName: 'الشورى',
    englishName: 'The Consultation',
    revelation: 'Meccan',
    ayahCount: 53,
  },
  {
    number: 43,
    name: 'Az-Zukhruf',
    arabicName: 'الزخرف',
    englishName: 'The Ornaments of Gold',
    revelation: 'Meccan',
    ayahCount: 89,
  },
  {
    number: 44,
    name: 'Ad-Dukhan',
    arabicName: 'الدخان',
    englishName: 'The Smoke',
    revelation: 'Meccan',
    ayahCount: 59,
  },
  {
    number: 45,
    name: 'Al-Jathiyah',
    arabicName: 'الجاثية',
    englishName: 'The Crouching',
    revelation: 'Meccan',
    ayahCount: 37,
  },
  {
    number: 46,
    name: 'Al-Ahqaf',
    arabicName: 'الأحقاف',
    englishName: 'The Wind-Curved Sandhills',
    revelation: 'Meccan',
    ayahCount: 35,
  },
  {
    number: 47,
    name: 'Muhammad',
    arabicName: 'محمد',
    englishName: 'Muhammad',
    revelation: 'Medinan',
    ayahCount: 38,
  },
  {
    number: 48,
    name: 'Al-Fath',
    arabicName: 'الفتح',
    englishName: 'The Victory',
    revelation: 'Medinan',
    ayahCount: 29,
  },
  {
    number: 49,
    name: 'Al-Hujurat',
    arabicName: 'الحجرات',
    englishName: 'The Rooms',
    revelation: 'Medinan',
    ayahCount: 18,
  },
  {
    number: 50,
    name: 'Qaf',
    arabicName: 'ق',
    englishName: 'Qaf',
    revelation: 'Meccan',
    ayahCount: 45,
  },
  {
    number: 51,
    name: 'Adh-Dhariyat',
    arabicName: 'الذاريات',
    englishName: 'The Winnowing Winds',
    revelation: 'Meccan',
    ayahCount: 60,
  },
  {
    number: 52,
    name: 'At-Tur',
    arabicName: 'الطور',
    englishName: 'The Mount',
    revelation: 'Meccan',
    ayahCount: 49,
  },
  {
    number: 53,
    name: 'An-Najm',
    arabicName: 'النجم',
    englishName: 'The Star',
    revelation: 'Meccan',
    ayahCount: 62,
  },
  {
    number: 54,
    name: 'Al-Qamar',
    arabicName: 'القمر',
    englishName: 'The Moon',
    revelation: 'Meccan',
    ayahCount: 55,
  },
  {
    number: 55,
    name: 'Ar-Rahman',
    arabicName: 'الرحمن',
    englishName: 'The Beneficent',
    revelation: 'Medinan',
    ayahCount: 78,
  },
  {
    number: 56,
    name: "Al-Waqi'ah",
    arabicName: 'الواقعة',
    englishName: 'The Inevitable',
    revelation: 'Meccan',
    ayahCount: 96,
  },
  {
    number: 57,
    name: 'Al-Hadid',
    arabicName: 'الحديد',
    englishName: 'The Iron',
    revelation: 'Medinan',
    ayahCount: 29,
  },
  {
    number: 58,
    name: 'Al-Mujadilah',
    arabicName: 'المجادلة',
    englishName: 'The Pleading Woman',
    revelation: 'Medinan',
    ayahCount: 22,
  },
  {
    number: 59,
    name: 'Al-Hashr',
    arabicName: 'الحشر',
    englishName: 'The Exile',
    revelation: 'Medinan',
    ayahCount: 24,
  },
  {
    number: 60,
    name: 'Al-Mumtahanah',
    arabicName: 'الممتحنة',
    englishName: 'She That Is To Be Examined',
    revelation: 'Medinan',
    ayahCount: 13,
  },
  {
    number: 61,
    name: 'As-Saff',
    arabicName: 'الصف',
    englishName: 'The Ranks',
    revelation: 'Medinan',
    ayahCount: 14,
  },
  {
    number: 62,
    name: "Al-Jumu'ah",
    arabicName: 'الجمعة',
    englishName: 'Friday',
    revelation: 'Medinan',
    ayahCount: 11,
  },
  {
    number: 63,
    name: 'Al-Munafiqun',
    arabicName: 'المنافقون',
    englishName: 'The Hypocrites',
    revelation: 'Medinan',
    ayahCount: 11,
  },
  {
    number: 64,
    name: 'At-Taghabun',
    arabicName: 'التغابن',
    englishName: 'The Mutual Disillusion',
    revelation: 'Medinan',
    ayahCount: 18,
  },
  {
    number: 65,
    name: 'At-Talaq',
    arabicName: 'الطلاق',
    englishName: 'The Divorce',
    revelation: 'Medinan',
    ayahCount: 12,
  },
  {
    number: 66,
    name: 'At-Tahrim',
    arabicName: 'التحريم',
    englishName: 'The Prohibition',
    revelation: 'Medinan',
    ayahCount: 12,
  },
  {
    number: 67,
    name: 'Al-Mulk',
    arabicName: 'الملك',
    englishName: 'The Sovereignty',
    revelation: 'Meccan',
    ayahCount: 30,
  },
  {
    number: 68,
    name: 'Al-Qalam',
    arabicName: 'القلم',
    englishName: 'The Pen',
    revelation: 'Meccan',
    ayahCount: 52,
  },
  {
    number: 69,
    name: 'Al-Haqqah',
    arabicName: 'الحاقة',
    englishName: 'The Reality',
    revelation: 'Meccan',
    ayahCount: 52,
  },
  {
    number: 70,
    name: "Al-Ma'arij",
    arabicName: 'المعارج',
    englishName: 'The Ascending Stairways',
    revelation: 'Meccan',
    ayahCount: 44,
  },
  {
    number: 71,
    name: 'Nuh',
    arabicName: 'نوح',
    englishName: 'Noah',
    revelation: 'Meccan',
    ayahCount: 28,
  },
  {
    number: 72,
    name: 'Al-Jinn',
    arabicName: 'الجن',
    englishName: 'The Jinn',
    revelation: 'Meccan',
    ayahCount: 28,
  },
  {
    number: 73,
    name: 'Al-Muzzammil',
    arabicName: 'المزمل',
    englishName: 'The Enshrouded One',
    revelation: 'Meccan',
    ayahCount: 20,
  },
  {
    number: 74,
    name: 'Al-Muddaththir',
    arabicName: 'المدثر',
    englishName: 'The Cloaked One',
    revelation: 'Meccan',
    ayahCount: 56,
  },
  {
    number: 75,
    name: 'Al-Qiyamah',
    arabicName: 'القيامة',
    englishName: 'The Resurrection',
    revelation: 'Meccan',
    ayahCount: 40,
  },
  {
    number: 76,
    name: 'Al-Insan',
    arabicName: 'الإنسان',
    englishName: 'The Man',
    revelation: 'Medinan',
    ayahCount: 31,
  },
  {
    number: 77,
    name: 'Al-Mursalat',
    arabicName: 'المرسلات',
    englishName: 'Those Sent Forth',
    revelation: 'Meccan',
    ayahCount: 50,
  },
  {
    number: 78,
    name: 'An-Naba',
    arabicName: 'النبأ',
    englishName: 'The Tidings',
    revelation: 'Meccan',
    ayahCount: 40,
  },
  {
    number: 79,
    name: 'An-Naziat',
    arabicName: 'النازعات',
    englishName: 'Those Who Drag Forth',
    revelation: 'Meccan',
    ayahCount: 46,
  },
  {
    number: 80,
    name: 'Abasa',
    arabicName: 'عبس',
    englishName: 'He Frowned',
    revelation: 'Meccan',
    ayahCount: 42,
  },
  {
    number: 81,
    name: 'At-Takwir',
    arabicName: 'التكوير',
    englishName: 'The Overthrowing',
    revelation: 'Meccan',
    ayahCount: 29,
  },
  {
    number: 82,
    name: 'Al-Infitar',
    arabicName: 'الانفطار',
    englishName: 'The Cleaving',
    revelation: 'Meccan',
    ayahCount: 19,
  },
  {
    number: 83,
    name: 'Al-Mutaffifin',
    arabicName: 'المطففين',
    englishName: 'The Defrauding',
    revelation: 'Meccan',
    ayahCount: 36,
  },
  {
    number: 84,
    name: 'Al-Inshiqaq',
    arabicName: 'الانشقاق',
    englishName: 'The Sundering',
    revelation: 'Meccan',
    ayahCount: 25,
  },
  {
    number: 85,
    name: 'Al-Buruj',
    arabicName: 'البروج',
    englishName: 'The Mansions of the Stars',
    revelation: 'Meccan',
    ayahCount: 22,
  },
  {
    number: 86,
    name: 'At-Tariq',
    arabicName: 'الطارق',
    englishName: 'The Nightcomer',
    revelation: 'Meccan',
    ayahCount: 17,
  },
  {
    number: 87,
    name: "Al-A'la",
    arabicName: 'الأعلى',
    englishName: 'The Most High',
    revelation: 'Meccan',
    ayahCount: 19,
  },
  {
    number: 88,
    name: 'Al-Ghashiyah',
    arabicName: 'الغاشية',
    englishName: 'The Overwhelming',
    revelation: 'Meccan',
    ayahCount: 26,
  },
  {
    number: 89,
    name: 'Al-Fajr',
    arabicName: 'الفجر',
    englishName: 'The Dawn',
    revelation: 'Meccan',
    ayahCount: 30,
  },
  {
    number: 90,
    name: 'Al-Balad',
    arabicName: 'البلد',
    englishName: 'The City',
    revelation: 'Meccan',
    ayahCount: 20,
  },
  {
    number: 91,
    name: 'Ash-Shams',
    arabicName: 'الشمس',
    englishName: 'The Sun',
    revelation: 'Meccan',
    ayahCount: 15,
  },
  {
    number: 92,
    name: 'Al-Layl',
    arabicName: 'الليل',
    englishName: 'The Night',
    revelation: 'Meccan',
    ayahCount: 21,
  },
  {
    number: 93,
    name: 'Ad-Duha',
    arabicName: 'الضحى',
    englishName: 'The Morning Hours',
    revelation: 'Meccan',
    ayahCount: 11,
  },
  {
    number: 94,
    name: 'Ash-Sharh',
    arabicName: 'الشرح',
    englishName: 'The Relief',
    revelation: 'Meccan',
    ayahCount: 8,
  },
  {
    number: 95,
    name: 'At-Tin',
    arabicName: 'التين',
    englishName: 'The Fig',
    revelation: 'Meccan',
    ayahCount: 8,
  },
  {
    number: 96,
    name: "Al-Alaq",
    arabicName: 'العلق',
    englishName: 'The Clot',
    revelation: 'Meccan',
    ayahCount: 19,
  },
  {
    number: 97,
    name: 'Al-Qadr',
    arabicName: 'القدر',
    englishName: 'The Power',
    revelation: 'Meccan',
    ayahCount: 5,
  },
  {
    number: 98,
    name: 'Al-Bayyinah',
    arabicName: 'البينة',
    englishName: 'The Clear Evidence',
    revelation: 'Medinan',
    ayahCount: 8,
  },
  {
    number: 99,
    name: 'Az-Zalzalah',
    arabicName: 'الزلزلة',
    englishName: 'The Earthquake',
    revelation: 'Medinan',
    ayahCount: 8,
  },
  {
    number: 100,
    name: 'Al-Adiyat',
    arabicName: 'العاديات',
    englishName: 'The Courser',
    revelation: 'Meccan',
    ayahCount: 11,
  },
  {
    number: 101,
    name: "Al-Qari'ah",
    arabicName: 'القارعة',
    englishName: 'The Striking Hour',
    revelation: 'Meccan',
    ayahCount: 11,
  },
  {
    number: 102,
    name: 'At-Takathur',
    arabicName: 'التكاثر',
    englishName: 'The Rivalry in World Increase',
    revelation: 'Meccan',
    ayahCount: 8,
  },
  {
    number: 103,
    name: 'Al-Asr',
    arabicName: 'العصر',
    englishName: 'The Declining Day',
    revelation: 'Meccan',
    ayahCount: 3,
  },
  {
    number: 104,
    name: 'Al-Humazah',
    arabicName: 'الهمزة',
    englishName: 'The Traducer',
    revelation: 'Meccan',
    ayahCount: 9,
  },
  {
    number: 105,
    name: 'Al-Fil',
    arabicName: 'الفيل',
    englishName: 'The Elephant',
    revelation: 'Meccan',
    ayahCount: 5,
  },
  {
    number: 106,
    name: 'Quraysh',
    arabicName: 'قريش',
    englishName: 'Quraysh',
    revelation: 'Meccan',
    ayahCount: 4,
  },
  {
    number: 107,
    name: "Al-Ma'un",
    arabicName: 'الماعون',
    englishName: 'The Small Kindnesses',
    revelation: 'Meccan',
    ayahCount: 7,
  },
  {
    number: 108,
    name: 'Al-Kawthar',
    arabicName: 'الكوثر',
    englishName: 'The Abundance',
    revelation: 'Meccan',
    ayahCount: 3,
  },
  {
    number: 109,
    name: 'Al-Kafirun',
    arabicName: 'الكافرون',
    englishName: 'The Disbelievers',
    revelation: 'Meccan',
    ayahCount: 6,
  },
  {
    number: 110,
    name: 'An-Nasr',
    arabicName: 'النصر',
    englishName: 'The Divine Support',
    revelation: 'Medinan',
    ayahCount: 3,
  },
  {
    number: 111,
    name: 'Al-Masad',
    arabicName: 'المسد',
    englishName: 'The Palm Fiber',
    revelation: 'Meccan',
    ayahCount: 5,
  },
  {
    number: 112,
    name: 'Al-Ikhlas',
    arabicName: 'الإخلاص',
    englishName: 'The Sincerity',
    revelation: 'Meccan',
    ayahCount: 4,
  },
  {
    number: 113,
    name: 'Al-Falaq',
    arabicName: 'الفلق',
    englishName: 'The Daybreak',
    revelation: 'Meccan',
    ayahCount: 5,
  },
  {
    number: 114,
    name: 'An-Nas',
    arabicName: 'الناس',
    englishName: 'Mankind',
    revelation: 'Meccan',
    ayahCount: 6,
  },
];
